---
- quote: "< drogoh> ack, zak attack!"
  added_by: s
  created_at: 2014-10-26 06:01:41.556455656 +01:00
  deleted: false
  id: 1
- quote: "[07:46] < sc`> if you don't squeak, they won't give you any grease"
  added_by: s
  created_at: 2014-10-29 15:47:54.262539911 +01:00
  deleted: false
  id: 2
- quote: "[15:11] <@Morty> It's all you'll ever have, Big Bird."
  added_by: s
  created_at: 2014-11-05 00:14:20.269533811 +01:00
  deleted: false
  id: 3
- quote: "< m> I just watch people porn"
  added_by: s
  created_at: 2014-11-08 01:30:58.604421317 +01:00
  deleted: false
  id: 4
- quote: "<+m> balls I went down."
  added_by: s
  created_at: 2014-11-09 05:31:48.767159968 +01:00
  deleted: false
  id: 5
